# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginMainWindow(object):
    def setupUi(self, LoginMainWindow):
        LoginMainWindow.setObjectName("LoginMainWindow")
        LoginMainWindow.resize(592, 577)
        LoginMainWindow.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgb(255, 2, 57), stop:1 rgb(68, 255, 16));\n"
"color: white")
        self.centralwidget = QtWidgets.QWidget(LoginMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 10, 221, 161))
        font = QtGui.QFont()
        font.setPointSize(75)
        font.setUnderline(False)
        self.label.setFont(font)
        self.label.setStyleSheet("#label{\n"
"color: rgb(255, 255, 255);\n"
"border: 4px Solid rgb(48, 252, 255);\n"
"border-radius: 60px;\n"
"}")
        self.label.setObjectName("label")
        self.New_btn = QtWidgets.QPushButton(self.centralwidget)
        self.New_btn.setGeometry(QtCore.QRect(170, 370, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(True)
        self.New_btn.setFont(font)
        self.New_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.New_btn.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgb(255, 2, 57), stop:1 rgb(68, 255, 16));\n"
"border: 0;\n"
"color: blue\n"
"\n"
"")
        self.New_btn.setObjectName("New_btn")
        self.Email_input = QtWidgets.QLineEdit(self.centralwidget)
        self.Email_input.setGeometry(QtCore.QRect(85, 190, 460, 70))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.Email_input.setFont(font)
        self.Email_input.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: white;\n"
"padding-bottom:7px;\n"
"color: white;\n"
"background-color: rgb(181, 181, 181);")
        self.Email_input.setText("")
        self.Email_input.setObjectName("Email_input")
        self.Password_input = QtWidgets.QLineEdit(self.centralwidget)
        self.Password_input.setGeometry(QtCore.QRect(85, 280, 460, 70))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.Password_input.setFont(font)
        self.Password_input.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.Password_input.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: white;\n"
"padding-bottom:7px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(181, 181, 181);")
        self.Password_input.setText("")
        self.Password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password_input.setObjectName("Password_input")
        self.Voyageur_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Voyageur_btn.setGeometry(QtCore.QRect(90, 430, 200, 71))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.Voyageur_btn.setFont(font)
        self.Voyageur_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Voyageur_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);\n"
"")
        self.Voyageur_btn.setObjectName("Voyageur_btn")
        self.Vol_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Vol_btn.setGeometry(QtCore.QRect(340, 430, 200, 71))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.Vol_btn.setFont(font)
        self.Vol_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Vol_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(43, 57, 255);\n"
"")
        self.Vol_btn.setObjectName("Vol_btn")
        LoginMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LoginMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 592, 29))
        self.menubar.setObjectName("menubar")
        LoginMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LoginMainWindow)
        self.statusbar.setObjectName("statusbar")
        LoginMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LoginMainWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginMainWindow)

    def retranslateUi(self, LoginMainWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginMainWindow.setWindowTitle(_translate("LoginMainWindow", "MainWindow"))
        self.label.setText(_translate("LoginMainWindow", ""))
        self.New_btn.setText(_translate("LoginMainWindow", "Creat New account"))
        self.Email_input.setPlaceholderText(_translate("LoginMainWindow", "Email                                   "))
        self.Password_input.setPlaceholderText(_translate("LoginMainWindow", "Password                              "))
        self.Voyageur_btn.setText(_translate("LoginMainWindow", "Voyageur"))
        self.Vol_btn.setText(_translate("LoginMainWindow", "Vol"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     LoginMainWindow = QtWidgets.QMainWindow()
#     ui = Ui_LoginMainWindow()
#     ui.setupUi(LoginMainWindow)
#     LoginMainWindow.show()
#     sys.exit(app.exec_())
