# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'volScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VolMainWindow(object):
    def setupUi(self, VolMainWindow):
        VolMainWindow.setObjectName("VolMainWindow")
        VolMainWindow.resize(592, 576)
        VolMainWindow.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #00F260, stop:1 #0575E6);\n"
"")
        self.centralwidget = QtWidgets.QWidget(VolMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 10, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:  rgb(1, 35, 255);\n"
"background-color: none;")
        self.label_2.setObjectName("label_2")
        self.Add_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Add_btn.setGeometry(QtCore.QRect(20, 420, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.Add_btn.setFont(font)
        self.Add_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Add_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 170, 0);\n"
"")
        self.Add_btn.setObjectName("Add_btn")
        self.Destination_input = QtWidgets.QLineEdit(self.centralwidget)
        self.Destination_input.setGeometry(QtCore.QRect(310, 110, 261, 70))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.Destination_input.setFont(font)
        self.Destination_input.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: white;\n"
"padding-bottom:7px;\n"
"color: rgb(255, 255, 255);\n"
"background-color:rgb(168, 168, 168)")
        self.Destination_input.setText("")
        self.Destination_input.setObjectName("Destination_input")
        self.Delete_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Delete_btn.setGeometry(QtCore.QRect(210, 420, 170, 71))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.Delete_btn.setFont(font)
        self.Delete_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Delete_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);\n"
"")
        self.Delete_btn.setObjectName("Delete_btn")
        self.Date_input = QtWidgets.QLineEdit(self.centralwidget)
        self.Date_input.setGeometry(QtCore.QRect(20, 210, 261, 70))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.Date_input.setFont(font)
        self.Date_input.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: white;\n"
"padding-bottom:7px;\n"
"color: rgb(255, 255, 255);\n"
"background-color:rgb(168, 168, 168)")
        self.Date_input.setText("")
        self.Date_input.setObjectName("Date_input")
        self.Duree_input = QtWidgets.QLineEdit(self.centralwidget)
        self.Duree_input.setGeometry(QtCore.QRect(311, 210, 261, 70))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.Duree_input.setFont(font)
        self.Duree_input.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: white;\n"
"padding-bottom:7px;\n"
"color: rgb(255, 255, 255);\n"
"background-color:rgb(168, 168, 168)")
        self.Duree_input.setText("")
        self.Duree_input.setObjectName("Duree_input")
        self.numDavion_input = QtWidgets.QLineEdit(self.centralwidget)
        self.numDavion_input.setGeometry(QtCore.QRect(22, 310, 551, 70))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.numDavion_input.setFont(font)
        self.numDavion_input.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: white;\n"
"padding-bottom:7px;\n"
"color: rgb(255, 255, 255);\n"
"background-color:rgb(168, 168, 168)")
        self.numDavion_input.setText("")
        self.numDavion_input.setObjectName("numDavion_input")
        self.Search_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Search_btn.setGeometry(QtCore.QRect(400, 420, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.Search_btn.setFont(font)
        self.Search_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Search_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(43, 57, 255);\n"
"")
        self.Search_btn.setObjectName("Search_btn")
        self.Origine_input = QtWidgets.QLineEdit(self.centralwidget)
        self.Origine_input.setGeometry(QtCore.QRect(20, 110, 261, 70))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.Origine_input.setFont(font)
        self.Origine_input.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: white;\n"
"padding-bottom:7px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(168, 168, 168);\n"
"\n"
"\n"
"")
        self.Origine_input.setText("")
        self.Origine_input.setObjectName("Origine_input")
        VolMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VolMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 592, 29))
        self.menubar.setObjectName("menubar")
        VolMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VolMainWindow)
        self.statusbar.setObjectName("statusbar")
        VolMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(VolMainWindow)
        QtCore.QMetaObject.connectSlotsByName(VolMainWindow)

    def retranslateUi(self, VolMainWindow):
        _translate = QtCore.QCoreApplication.translate
        VolMainWindow.setWindowTitle(_translate("VolMainWindow", "MainWindow"))
        self.label_2.setText(_translate("VolMainWindow", "Vol  "))
        self.Add_btn.setText(_translate("VolMainWindow", "Add "))
        self.Destination_input.setPlaceholderText(_translate("VolMainWindow", "Destination"))
        self.Delete_btn.setText(_translate("VolMainWindow", "Delete "))
        self.Date_input.setPlaceholderText(_translate("VolMainWindow", "Date"))
        self.Duree_input.setPlaceholderText(_translate("VolMainWindow", "Durée"))
        self.numDavion_input.setPlaceholderText(_translate("VolMainWindow", "Numéro D\'avion"))
        self.Search_btn.setText(_translate("VolMainWindow", "Search "))
        self.Origine_input.setPlaceholderText(_translate("VolMainWindow", "Origine"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VolMainWindow = QtWidgets.QMainWindow()
    ui = Ui_VolMainWindow()
    ui.setupUi(VolMainWindow)
    VolMainWindow.show()
    sys.exit(app.exec_())
