# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'voyogeurScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VoyageurMainWindow(object):
    def setupUi(self, VoyageurMainWindow):
        VoyageurMainWindow.setObjectName("VoyageurMainWindow")
        VoyageurMainWindow.resize(590, 591)
        VoyageurMainWindow.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 blue, stop:1 red);\n"
"")
        self.centralwidget = QtWidgets.QWidget(VoyageurMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tel_input = QtWidgets.QLineEdit(self.centralwidget)
        self.tel_input.setGeometry(QtCore.QRect(20, 270, 261, 70))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.tel_input.setFont(font)
        self.tel_input.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: white;\n"
"padding-bottom:7px;\n"
"color: rgb(255, 255, 255);\n"
"background-color:rgb(168, 168, 168)")
        self.tel_input.setText("")
        self.tel_input.setObjectName("tel_input")
        self.Add_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Add_btn.setGeometry(QtCore.QRect(18, 450, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.Add_btn.setFont(font)
        self.Add_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Add_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 170, 0);\n"
"")
        self.Add_btn.setObjectName("Add_btn")
        self.Nom_input = QtWidgets.QLineEdit(self.centralwidget)
        self.Nom_input.setGeometry(QtCore.QRect(20, 180, 261, 70))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.Nom_input.setFont(font)
        self.Nom_input.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: white;\n"
"padding-bottom:7px;\n"
"color: rgb(255, 255, 255);\n"
"background-color:rgb(168, 168, 168)")
        self.Nom_input.setText("")
        self.Nom_input.setObjectName("Nom_input")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(228, 0, 191, 71))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:  white;\n"
"background-color: none;")
        self.label_2.setObjectName("label_2")
        self.Search_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Search_btn.setGeometry(QtCore.QRect(398, 450, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.Search_btn.setFont(font)
        self.Search_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(43, 57, 255);\n"
"")
        self.Search_btn.setObjectName("Search_btn")
        self.Numero_input = QtWidgets.QLineEdit(self.centralwidget)
        self.Numero_input.setGeometry(QtCore.QRect(22, 91, 261, 70))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.Numero_input.setFont(font)
        self.Numero_input.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: white;\n"
"padding-bottom:7px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(168, 168, 168);\n"
"\n"
"\n"
"")
        self.Numero_input.setText("")
        self.Numero_input.setObjectName("Numero_input")
        self.prenom_input = QtWidgets.QLineEdit(self.centralwidget)
        self.prenom_input.setGeometry(QtCore.QRect(310, 180, 261, 70))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.prenom_input.setFont(font)
        self.prenom_input.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: white;\n"
"padding-bottom:7px;\n"
"color: rgb(255, 255, 255);\n"
"background-color:rgb(168, 168, 168)")
        self.prenom_input.setText("")
        self.prenom_input.setObjectName("prenom_input")
        self.Delete_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Delete_btn.setGeometry(QtCore.QRect(208, 450, 170, 71))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.Delete_btn.setFont(font)
        self.Delete_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Delete_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);\n"
"")
        self.Delete_btn.setObjectName("Delete_btn")
        self.Passeport_input = QtWidgets.QLineEdit(self.centralwidget)
        self.Passeport_input.setGeometry(QtCore.QRect(310, 90, 261, 70))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.Passeport_input.setFont(font)
        self.Passeport_input.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: white;\n"
"padding-bottom:7px;\n"
"color: rgb(255, 255, 255);\n"
"background-color:rgb(168, 168, 168)")
        self.Passeport_input.setText("")
        self.Passeport_input.setObjectName("Passeport_input")
        self.Adresse_input = QtWidgets.QLineEdit(self.centralwidget)
        self.Adresse_input.setGeometry(QtCore.QRect(310, 270, 261, 70))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.Adresse_input.setFont(font)
        self.Adresse_input.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: white;\n"
"padding-bottom:7px;\n"
"color: rgb(255, 255, 255);\n"
"background-color:rgb(168, 168, 168)")
        self.Adresse_input.setText("")
        self.Adresse_input.setObjectName("Adresse_input")
        self.Email_input = QtWidgets.QLineEdit(self.centralwidget)
        self.Email_input.setGeometry(QtCore.QRect(20, 360, 261, 70))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.Email_input.setFont(font)
        self.Email_input.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: white;\n"
"padding-bottom:7px;\n"
"color: rgb(255, 255, 255);\n"
"background-color:rgb(168, 168, 168)")
        self.Email_input.setText("")
        self.Email_input.setObjectName("Email_input")
        self.numVol_input = QtWidgets.QLineEdit(self.centralwidget)
        self.numVol_input.setGeometry(QtCore.QRect(310, 360, 261, 70))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.numVol_input.setFont(font)
        self.numVol_input.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: white;\n"
"padding-bottom:7px;\n"
"color: rgb(255, 255, 255);\n"
"background-color:rgb(168, 168, 168)")
        self.numVol_input.setText("")
        self.numVol_input.setObjectName("numVol_input")
        VoyageurMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VoyageurMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 590, 29))
        self.menubar.setObjectName("menubar")
        VoyageurMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VoyageurMainWindow)
        self.statusbar.setObjectName("statusbar")
        VoyageurMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(VoyageurMainWindow)
        QtCore.QMetaObject.connectSlotsByName(VoyageurMainWindow)

    def retranslateUi(self, VoyageurMainWindow):
        _translate = QtCore.QCoreApplication.translate
        VoyageurMainWindow.setWindowTitle(_translate("VoyageurMainWindow", "MainWindow"))
        self.tel_input.setPlaceholderText(_translate("VoyageurMainWindow", "Tel"))
        self.Add_btn.setText(_translate("VoyageurMainWindow", "Add "))
        self.Nom_input.setPlaceholderText(_translate("VoyageurMainWindow", "Nom"))
        self.label_2.setText(_translate("VoyageurMainWindow", "voyageur"))
        self.Search_btn.setText(_translate("VoyageurMainWindow", "Search "))
        self.Numero_input.setPlaceholderText(_translate("VoyageurMainWindow", "Numero"))
        self.prenom_input.setPlaceholderText(_translate("VoyageurMainWindow", "prenom"))
        self.Delete_btn.setText(_translate("VoyageurMainWindow", "Delete "))
        self.Passeport_input.setPlaceholderText(_translate("VoyageurMainWindow", "Passeport"))
        self.Adresse_input.setPlaceholderText(_translate("VoyageurMainWindow", "Adresse"))
        self.Email_input.setPlaceholderText(_translate("VoyageurMainWindow", "Email"))
        self.numVol_input.setPlaceholderText(_translate("VoyageurMainWindow", "N vol"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VoyageurMainWindow = QtWidgets.QMainWindow()
    ui = Ui_VoyageurMainWindow()
    ui.setupUi(VoyageurMainWindow)
    VoyageurMainWindow.show()
    sys.exit(app.exec_())
